import './styles/index.css'

export { VideoPlayer } from './components/VideoPlayer'
export type { VideoPlayerProps } from './components/VideoPlayer'
export type { ThumbnailTrack } from './components/ThumbnailPreview'
export type { SubtitleTrack } from './store/playerStore'
export type { PlayerEvent, PlayerEventType } from './types/events'
export type { PlayerFeatures } from './types/features'
export { DEMO_TENANT_ID } from './constants'
export { usePlayer } from './hooks/usePlayer'
export type { AIHighlight, AITranscriptWord, AIStatus } from './store/aiStore'
